/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PharmacyUI;

import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author hp
 */
public class FRAME12 extends javax.swing.JFrame {

    /**
     * Creates new form FRAME12
     */
    public FRAME12() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PMS");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 255, 255));
        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Enter the customer number");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton1))
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(13, 13, 13)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        FRAME10 jf10 = new FRAME10();
            jf10.show();
            
            dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         WriteToFile();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void WriteToFile() {
        int temp = Integer.parseInt(jTextField2.getText());
         jTextField2.setText("");
        if(temp == 1)
      {
        try {
        FileWriter WN = new FileWriter("f1Name.txt");
        FileWriter WID = new FileWriter("f1ID.txt");
        FileWriter WAdd = new FileWriter("f1Add.txt");
        FileWriter WNum = new FileWriter("f1Num.txt");
        WN.write("----");
        WID.write("----");
        WAdd.write("----");
        WNum.write("----");
        WNum.close();
        WAdd.close();
        WID.close();
        WN.close();
      } catch (IOException e) {
        System.out.println("An error occurred.");
        e.printStackTrace();
      }
     }
     else if(temp == 2)
      {
        try {
        FileWriter WN = new FileWriter("f2Name.txt");
        FileWriter WID = new FileWriter("f2ID.txt");
        FileWriter WAdd = new FileWriter("f2Add.txt");
        FileWriter WNum = new FileWriter("f2Num.txt");
        WN.write("----");
        WID.write("----");
        WAdd.write("----");
        WNum.write("----");
        WNum.close();
        WAdd.close();
        WID.close();
        WN.close();
      } catch (IOException e) {
        System.out.println("An error occurred.");
        e.printStackTrace();
      }
     }
      else if(temp == 3)
      {
        try {
        FileWriter WN = new FileWriter("f3Name.txt");
        FileWriter WID = new FileWriter("f3ID.txt");
        FileWriter WAdd = new FileWriter("f3Add.txt");
        FileWriter WNum = new FileWriter("f3Num.txt");
        WN.write("----");
        WID.write("----");
        WAdd.write("----");
        WNum.write("----");
        WNum.close();
        WAdd.close();
        WID.close();
        WN.close();
      } catch (IOException e) {
        System.out.println("An error occurred.");
        e.printStackTrace();
      }
     }
      else if(temp == 4)
      {
        try {
        FileWriter WN = new FileWriter("f4Name.txt");
        FileWriter WID = new FileWriter("f4ID.txt");
        FileWriter WAdd = new FileWriter("f4Add.txt");
        FileWriter WNum = new FileWriter("f4Num.txt");
        WN.write("----");
        WID.write("----");
        WAdd.write("----");
        WNum.write("----");
        WNum.close();
        WAdd.close();
        WID.close();
        WN.close();
      } catch (IOException e) {
        System.out.println("An error occurred.");
        e.printStackTrace();
      }
     }
      else if(temp == 5)
      {
        try {
        FileWriter WN = new FileWriter("f5Name.txt");
        FileWriter WID = new FileWriter("f5ID.txt");
        FileWriter WAdd = new FileWriter("f5Add.txt");
        FileWriter WNum = new FileWriter("f5Num.txt");
        WN.write("----");
        WID.write("----");
        WAdd.write("----");
        WNum.write("----");
        WNum.close();
        WAdd.close();
        WID.close();
        WN.close();
      } catch (IOException e) {
        System.out.println("An error occurred.");
        e.printStackTrace();
      }
     }
      else if(temp == 6)
      {
        try {
        FileWriter WN = new FileWriter("f6Name.txt");
        FileWriter WID = new FileWriter("f6ID.txt");
        FileWriter WAdd = new FileWriter("f6Add.txt");
        FileWriter WNum = new FileWriter("f6Num.txt");
        WN.write("----");
        WID.write("----");
        WAdd.write("----");
        WNum.write("----");
        WNum.close();
        WAdd.close();
        WID.close();
        WN.close();
      } catch (IOException e) {
        System.out.println("An error occurred.");
        e.printStackTrace();
      }
     }
      else if(temp == 7)
      {
        try {
        FileWriter WN = new FileWriter("f7Name.txt");
        FileWriter WID = new FileWriter("f7ID.txt");
        FileWriter WAdd = new FileWriter("f7Add.txt");
        FileWriter WNum = new FileWriter("f7Num.txt");
        WN.write("----");
        WID.write("----");
        WAdd.write("----");
        WNum.write("----");
        WNum.close();
        WAdd.close();
        WID.close();
        WN.close();
      } catch (IOException e) {
        System.out.println("An error occurred.");
        e.printStackTrace();
      }
     }
      else if(temp == 8)
      {
        try {
        FileWriter WN = new FileWriter("f8Name.txt");
        FileWriter WID = new FileWriter("f8ID.txt");
        FileWriter WAdd = new FileWriter("f8Add.txt");
        FileWriter WNum = new FileWriter("f8Num.txt");
        WN.write("----");
        WID.write("----");
        WAdd.write("----");
        WNum.write("----");
        WNum.close();
        WAdd.close();
        WID.close();
        WN.close();
      } catch (IOException e) {
        System.out.println("An error occurred.");
        e.printStackTrace();
      }
     }
      else if(temp == 9)
      {
        try {
        FileWriter WN = new FileWriter("f9Name.txt");
        FileWriter WID = new FileWriter("f9ID.txt");
        FileWriter WAdd = new FileWriter("f9Add.txt");
        FileWriter WNum = new FileWriter("f9Num.txt");
        WN.write("----");
        WID.write("----");
        WAdd.write("----");
        WNum.write("----");
        WNum.close();
        WAdd.close();
        WID.close();
        WN.close();
      } catch (IOException e) {
        System.out.println("An error occurred.");
        e.printStackTrace();
      }
     }
      else if(temp == 10)
      {
        try {
        FileWriter WN = new FileWriter("f10Name.txt");
        FileWriter WID = new FileWriter("f10ID.txt");
        FileWriter WAdd = new FileWriter("f10Add.txt");
        FileWriter WNum = new FileWriter("f10Num.txt");
        WN.write("----");
        WID.write("----");
        WAdd.write("----");
        WNum.write("----");
        WNum.close();
        WAdd.close();
        WID.close();
        WN.close();
      } catch (IOException e) {
        System.out.println("An error occurred.");
        e.printStackTrace();
      }
      }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRAME12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRAME12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRAME12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRAME12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRAME12().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
