/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PharmacyUI;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

/**
 *
 * @author hp
 */
public class FRAME11 extends javax.swing.JFrame {

    /**
     * Creates new form JFRAME6
     */
    public FRAME11() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField(15);
        jTextField14 = new javax.swing.JTextField(15);
        jTextField15 = new javax.swing.JTextField(15);
        jTextField16 = new javax.swing.JTextField(15);
        jTextField17 = new javax.swing.JTextField(15);
        jTextField18 = new javax.swing.JTextField(15);
        jTextField19 = new javax.swing.JTextField(15);
        jTextField20 = new javax.swing.JTextField(15);
        jTextField22 = new javax.swing.JTextField(15);
        jTextField32 = new javax.swing.JTextField(15);
        ID10 = new javax.swing.JTextField(10);
        ID6 = new javax.swing.JTextField(10);
        ID1 = new javax.swing.JTextField(10);
        ID3 = new javax.swing.JTextField(10);
        ID4 = new javax.swing.JTextField(10);
        ID5 = new javax.swing.JTextField(10);
        jLabel5 = new javax.swing.JLabel();
        ID2 = new javax.swing.JTextField(10);
        ID7 = new javax.swing.JTextField(10);
        ID8 = new javax.swing.JTextField(10);
        ID9 = new javax.swing.JTextField(10);
        Num10 = new javax.swing.JTextField(15);
        Num6 = new javax.swing.JTextField(15);
        Num1 = new javax.swing.JTextField(15);
        Num3 = new javax.swing.JTextField(15);
        Num4 = new javax.swing.JTextField(15);
        Num5 = new javax.swing.JTextField(15);
        jLabel6 = new javax.swing.JLabel();
        Num2 = new javax.swing.JTextField(15);
        Num7 = new javax.swing.JTextField(15);
        Num8 = new javax.swing.JTextField(15);
        Num9 = new javax.swing.JTextField(15);
        Add10 = new javax.swing.JTextField(25);
        Add6 = new javax.swing.JTextField(25);
        Add1 = new javax.swing.JTextField(25);
        Add3 = new javax.swing.JTextField(25);
        Add4 = new javax.swing.JTextField(25);
        Add5 = new javax.swing.JTextField(25);
        jLabel7 = new javax.swing.JLabel();
        Add2 = new javax.swing.JTextField(25);
        Add7 = new javax.swing.JTextField(25);
        Add8 = new javax.swing.JTextField(25);
        Add9 = new javax.swing.JTextField(25);
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PMS");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(102, 204, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Customer's ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 26, 154, 25));

        jLabel3.setBackground(new java.awt.Color(102, 204, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("# No.");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 67, -1));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(153, 255, 255));
        jTextField4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("3");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 149, 67, 32));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(153, 255, 255));
        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("4");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 187, 67, 32));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(153, 255, 255));
        jTextField6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("5");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 225, 67, 32));

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(153, 255, 255));
        jTextField7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("2");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 111, 67, 32));

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(153, 255, 255));
        jTextField8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("7");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 302, 67, 32));

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(153, 255, 255));
        jTextField9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("8");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 67, 32));

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(153, 255, 255));
        jTextField10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("9");
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 378, 67, 32));

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(153, 255, 255));
        jTextField11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("10");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 416, 67, 32));

        jTextField12.setEditable(false);
        jTextField12.setBackground(new java.awt.Color(153, 255, 255));
        jTextField12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("6");
        jTextField12.setToolTipText("");
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 263, 67, 32));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(153, 255, 255));
        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("1");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 73, 67, 32));

        jTextField13.setEditable(false);
        jTextField13.setBackground(new java.awt.Color(153, 255, 255));
        jTextField13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 111, 184, 32));

        jTextField14.setEditable(false);
        jTextField14.setBackground(new java.awt.Color(153, 255, 255));
        jTextField14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 301, 184, 32));

        jTextField15.setEditable(false);
        jTextField15.setBackground(new java.awt.Color(153, 255, 255));
        jTextField15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 339, 184, 32));

        jTextField16.setEditable(false);
        jTextField16.setBackground(new java.awt.Color(153, 255, 255));
        jTextField16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 377, 184, 32));

        jTextField17.setEditable(false);
        jTextField17.setBackground(new java.awt.Color(153, 255, 255));
        jTextField17.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 415, 184, 32));

        jTextField18.setEditable(false);
        jTextField18.setBackground(new java.awt.Color(153, 255, 255));
        jTextField18.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 263, 184, 32));

        jTextField19.setEditable(false);
        jTextField19.setBackground(new java.awt.Color(153, 255, 255));
        jTextField19.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        jTextField19.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextField19PropertyChange(evt);
            }
        });
        jPanel2.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 73, 184, 32));

        jTextField20.setEditable(false);
        jTextField20.setBackground(new java.awt.Color(153, 255, 255));
        jTextField20.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 149, 184, 32));

        jTextField22.setEditable(false);
        jTextField22.setBackground(new java.awt.Color(153, 255, 255));
        jTextField22.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 187, 184, 32));

        jTextField32.setEditable(false);
        jTextField32.setBackground(new java.awt.Color(153, 255, 255));
        jTextField32.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField32ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 225, 184, 32));

        ID10.setEditable(false);
        ID10.setBackground(new java.awt.Color(153, 255, 255));
        ID10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ID10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ID10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID10ActionPerformed(evt);
            }
        });
        jPanel2.add(ID10, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 415, 184, 32));

        ID6.setEditable(false);
        ID6.setBackground(new java.awt.Color(153, 255, 255));
        ID6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ID6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ID6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID6ActionPerformed(evt);
            }
        });
        jPanel2.add(ID6, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 263, 184, 32));

        ID1.setEditable(false);
        ID1.setBackground(new java.awt.Color(153, 255, 255));
        ID1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ID1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID1ActionPerformed(evt);
            }
        });
        jPanel2.add(ID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 73, 184, 32));

        ID3.setEditable(false);
        ID3.setBackground(new java.awt.Color(153, 255, 255));
        ID3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ID3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ID3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID3ActionPerformed(evt);
            }
        });
        jPanel2.add(ID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 149, 184, 32));

        ID4.setEditable(false);
        ID4.setBackground(new java.awt.Color(153, 255, 255));
        ID4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ID4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ID4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID4ActionPerformed(evt);
            }
        });
        jPanel2.add(ID4, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 187, 184, 32));

        ID5.setEditable(false);
        ID5.setBackground(new java.awt.Color(153, 255, 255));
        ID5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ID5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ID5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID5ActionPerformed(evt);
            }
        });
        jPanel2.add(ID5, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 225, 184, 32));

        jLabel5.setBackground(new java.awt.Color(102, 204, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Customer's Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 26, 154, 25));

        ID2.setEditable(false);
        ID2.setBackground(new java.awt.Color(153, 255, 255));
        ID2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ID2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID2ActionPerformed(evt);
            }
        });
        jPanel2.add(ID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 111, 184, 32));

        ID7.setEditable(false);
        ID7.setBackground(new java.awt.Color(153, 255, 255));
        ID7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ID7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ID7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID7ActionPerformed(evt);
            }
        });
        jPanel2.add(ID7, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 301, 184, 32));

        ID8.setEditable(false);
        ID8.setBackground(new java.awt.Color(153, 255, 255));
        ID8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ID8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ID8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID8ActionPerformed(evt);
            }
        });
        jPanel2.add(ID8, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 339, 184, 32));

        ID9.setEditable(false);
        ID9.setBackground(new java.awt.Color(153, 255, 255));
        ID9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ID9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ID9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID9ActionPerformed(evt);
            }
        });
        jPanel2.add(ID9, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 377, 184, 32));

        Num10.setEditable(false);
        Num10.setBackground(new java.awt.Color(153, 255, 255));
        Num10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Num10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Num10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num10ActionPerformed(evt);
            }
        });
        jPanel2.add(Num10, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 415, 184, 32));

        Num6.setEditable(false);
        Num6.setBackground(new java.awt.Color(153, 255, 255));
        Num6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Num6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num6ActionPerformed(evt);
            }
        });
        jPanel2.add(Num6, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 263, 184, 32));

        Num1.setEditable(false);
        Num1.setBackground(new java.awt.Color(153, 255, 255));
        Num1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Num1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num1ActionPerformed(evt);
            }
        });
        jPanel2.add(Num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 73, 184, 32));

        Num3.setEditable(false);
        Num3.setBackground(new java.awt.Color(153, 255, 255));
        Num3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Num3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num3ActionPerformed(evt);
            }
        });
        jPanel2.add(Num3, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 149, 184, 32));

        Num4.setEditable(false);
        Num4.setBackground(new java.awt.Color(153, 255, 255));
        Num4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Num4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num4ActionPerformed(evt);
            }
        });
        jPanel2.add(Num4, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 187, 184, 32));

        Num5.setEditable(false);
        Num5.setBackground(new java.awt.Color(153, 255, 255));
        Num5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Num5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num5ActionPerformed(evt);
            }
        });
        jPanel2.add(Num5, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 225, 184, 32));

        jLabel6.setBackground(new java.awt.Color(102, 204, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Customer's Phone Number");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 26, 184, 25));

        Num2.setEditable(false);
        Num2.setBackground(new java.awt.Color(153, 255, 255));
        Num2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Num2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num2ActionPerformed(evt);
            }
        });
        jPanel2.add(Num2, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 111, 184, 32));

        Num7.setEditable(false);
        Num7.setBackground(new java.awt.Color(153, 255, 255));
        Num7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Num7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num7ActionPerformed(evt);
            }
        });
        jPanel2.add(Num7, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 301, 184, 32));

        Num8.setEditable(false);
        Num8.setBackground(new java.awt.Color(153, 255, 255));
        Num8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Num8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num8ActionPerformed(evt);
            }
        });
        jPanel2.add(Num8, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 339, 184, 32));

        Num9.setEditable(false);
        Num9.setBackground(new java.awt.Color(153, 255, 255));
        Num9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Num9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num9ActionPerformed(evt);
            }
        });
        jPanel2.add(Num9, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 377, 184, 32));

        Add10.setEditable(false);
        Add10.setBackground(new java.awt.Color(153, 255, 255));
        Add10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Add10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Add10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add10ActionPerformed(evt);
            }
        });
        jPanel2.add(Add10, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 415, 184, 32));

        Add6.setEditable(false);
        Add6.setBackground(new java.awt.Color(153, 255, 255));
        Add6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Add6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Add6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add6ActionPerformed(evt);
            }
        });
        jPanel2.add(Add6, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 263, 184, 32));

        Add1.setEditable(false);
        Add1.setBackground(new java.awt.Color(153, 255, 255));
        Add1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Add1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add1ActionPerformed(evt);
            }
        });
        jPanel2.add(Add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 73, 184, 32));

        Add3.setEditable(false);
        Add3.setBackground(new java.awt.Color(153, 255, 255));
        Add3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Add3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Add3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add3ActionPerformed(evt);
            }
        });
        jPanel2.add(Add3, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 149, 184, 32));

        Add4.setEditable(false);
        Add4.setBackground(new java.awt.Color(153, 255, 255));
        Add4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Add4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Add4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add4ActionPerformed(evt);
            }
        });
        jPanel2.add(Add4, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 187, 184, 32));

        Add5.setEditable(false);
        Add5.setBackground(new java.awt.Color(153, 255, 255));
        Add5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Add5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Add5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add5ActionPerformed(evt);
            }
        });
        jPanel2.add(Add5, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 225, 184, 32));

        jLabel7.setBackground(new java.awt.Color(102, 204, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Customer's Address");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 26, 154, 25));

        Add2.setEditable(false);
        Add2.setBackground(new java.awt.Color(153, 255, 255));
        Add2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Add2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add2ActionPerformed(evt);
            }
        });
        jPanel2.add(Add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 111, 184, 32));

        Add7.setEditable(false);
        Add7.setBackground(new java.awt.Color(153, 255, 255));
        Add7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Add7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Add7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add7ActionPerformed(evt);
            }
        });
        jPanel2.add(Add7, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 301, 184, 32));

        Add8.setEditable(false);
        Add8.setBackground(new java.awt.Color(153, 255, 255));
        Add8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Add8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Add8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add8ActionPerformed(evt);
            }
        });
        jPanel2.add(Add8, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 339, 184, 32));

        Add9.setEditable(false);
        Add9.setBackground(new java.awt.Color(153, 255, 255));
        Add9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Add9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Add9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add9ActionPerformed(evt);
            }
        });
        jPanel2.add(Add9, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 377, 184, 32));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CUSTOMER DATA");

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("REFRESH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203)
                .addComponent(jButton2))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void jTextField32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField32ActionPerformed

    private void ID10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID10ActionPerformed

    private void ID6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID6ActionPerformed

    private void ID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID1ActionPerformed

    private void ID3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID3ActionPerformed

    private void ID4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID4ActionPerformed

    private void ID5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID5ActionPerformed

    private void ID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID2ActionPerformed

    private void ID7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID7ActionPerformed

    private void ID8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID8ActionPerformed

    private void ID9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID9ActionPerformed

    private void Num10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num10ActionPerformed

    private void Num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num6ActionPerformed

    private void Num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num1ActionPerformed

    private void Num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num3ActionPerformed

    private void Num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num4ActionPerformed

    private void Num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num5ActionPerformed

    private void Num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num2ActionPerformed

    private void Num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num7ActionPerformed

    private void Num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num8ActionPerformed

    private void Num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num9ActionPerformed

    private void Add10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add10ActionPerformed

    private void Add6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add6ActionPerformed

    private void Add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add1ActionPerformed

    private void Add3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add3ActionPerformed

    private void Add4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add4ActionPerformed

    private void Add5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add5ActionPerformed

    private void Add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add2ActionPerformed

    private void Add7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add7ActionPerformed

    private void Add8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add8ActionPerformed

    private void Add9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFRAME5 jf5 = new JFRAME5();
            jf5.show();
            
            dispose();                   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField19PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextField19PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19PropertyChange

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ReadFromFiles();
    }//GEN-LAST:event_jButton2ActionPerformed
    private void ReadFromFiles() {
        IsDisp = true;
            try {
            Scanner N1 = new Scanner(new File("f1Name.txt"));
            Scanner N2 = new Scanner(new File("f2Name.txt"));
            Scanner N3 = new Scanner(new File("f3Name.txt"));
            Scanner N4 = new Scanner(new File("f4Name.txt"));
            Scanner N5 = new Scanner(new File("f5Name.txt"));
            Scanner N6 = new Scanner(new File("f6Name.txt"));
            Scanner N7 = new Scanner(new File("f7Name.txt"));
            Scanner N8 = new Scanner(new File("f8Name.txt"));
            Scanner N9 = new Scanner(new File("f9Name.txt"));
            Scanner N10 = new Scanner(new File("f10Name.txt"));
            
            Scanner CID1 = new Scanner(new File("f1ID.txt"));
            Scanner CID2 = new Scanner(new File("f2ID.txt"));
            Scanner CID3 = new Scanner(new File("f3ID.txt"));
            Scanner CID4 = new Scanner(new File("f4ID.txt"));
            Scanner CID5 = new Scanner(new File("f5ID.txt"));
            Scanner CID6 = new Scanner(new File("f6ID.txt"));
            Scanner CID7 = new Scanner(new File("f7ID.txt"));
            Scanner CID8 = new Scanner(new File("f8ID.txt"));
            Scanner CID9 = new Scanner(new File("f9ID.txt"));
            Scanner CID10 = new Scanner(new File("f10ID.txt"));
            
            Scanner CAdd1 = new Scanner(new File("f1Add.txt"));
            Scanner CAdd2 = new Scanner(new File("f2Add.txt"));
            Scanner CAdd3 = new Scanner(new File("f3Add.txt"));
            Scanner CAdd4 = new Scanner(new File("f4Add.txt"));
            Scanner CAdd5 = new Scanner(new File("f5Add.txt"));
            Scanner CAdd6 = new Scanner(new File("f6Add.txt"));
            Scanner CAdd7 = new Scanner(new File("f7Add.txt"));
            Scanner CAdd8 = new Scanner(new File("f8Add.txt"));
            Scanner CAdd9 = new Scanner(new File("f9Add.txt"));
            Scanner CAdd10 = new Scanner(new File("f10Add.txt"));
            
            Scanner CNum1 = new Scanner(new File("f1Num.txt"));
            Scanner CNum2 = new Scanner(new File("f2Num.txt"));
            Scanner CNum3 = new Scanner(new File("f3Num.txt"));
            Scanner CNum4 = new Scanner(new File("f4Num.txt"));
            Scanner CNum5 = new Scanner(new File("f5Num.txt"));
            Scanner CNum6 = new Scanner(new File("f6Num.txt"));
            Scanner CNum7 = new Scanner(new File("f7Num.txt"));
            Scanner CNum8 = new Scanner(new File("f8Num.txt"));
            Scanner CNum9 = new Scanner(new File("f9Num.txt"));
            Scanner CNum10 = new Scanner(new File("f10Num.txt"));
            while (IsDisp) {
              String D1 = N1.nextLine();
              String D2 = N2.nextLine();
              String D3 = N3.nextLine();
              String D4 = N4.nextLine();
              String D5 = N5.nextLine();
              String D6 = N6.nextLine();
              String D7 = N7.nextLine();
              String D8 = N8.nextLine();
              String D9 = N9.nextLine();
              String D10 = N10.nextLine();
              
              String D11 = CID1.nextLine();
              String D12 = CID2.nextLine();
              String D13 = CID3.nextLine();
              String D14 = CID4.nextLine();
              String D15 = CID5.nextLine();
              String D16 = CID6.nextLine();
              String D17 = CID7.nextLine();
              String D18 = CID8.nextLine();
              String D19 = CID9.nextLine();
              String D20 = CID10.nextLine();
              
              String D21 = CAdd1.nextLine();
              String D22 = CAdd2.nextLine();
              String D23 = CAdd3.nextLine();
              String D24 = CAdd4.nextLine();
              String D25 = CAdd5.nextLine();
              String D26 = CAdd6.nextLine();
              String D27 = CAdd7.nextLine();
              String D28 = CAdd8.nextLine();
              String D29 = CAdd9.nextLine();
              String D30 = CAdd10.nextLine();
              
              String D31 = CNum1.nextLine();
              String D32 = CNum2.nextLine();
              String D33 = CNum3.nextLine();
              String D34 = CNum4.nextLine();
              String D35 = CNum5.nextLine();
              String D36 = CNum6.nextLine();
              String D37 = CNum7.nextLine();
              String D38 = CNum8.nextLine();
              String D39 = CNum9.nextLine();
              String D40 = CNum10.nextLine();
              
              jTextField19.setText(D1);
              jTextField13.setText(D2);
              jTextField20.setText(D3);
              jTextField22.setText(D4);
              jTextField32.setText(D5);
              jTextField18.setText(D6);
              jTextField14.setText(D7);
              jTextField15.setText(D8);
              jTextField16.setText(D9);
              jTextField17.setText(D10);
              
              ID1.setText(D11);
              ID2.setText(D12);
              ID3.setText(D13);
              ID4.setText(D14);
              ID5.setText(D15);
              ID6.setText(D16);
              ID7.setText(D17);
              ID8.setText(D18);
              ID9.setText(D19);
              ID10.setText(D20);
              
              Add1.setText(D21);
              Add2.setText(D22);
              Add3.setText(D23);
              Add4.setText(D24);
              Add5.setText(D25);
              Add6.setText(D26);
              Add7.setText(D27);
              Add8.setText(D28);
              Add9.setText(D29);
              Add10.setText(D30);              
              
              Num1.setText(D31);
              Num2.setText(D32);
              Num3.setText(D33);
              Num4.setText(D34);
              Num5.setText(D35);
              Num6.setText(D36);
              Num7.setText(D37);
              Num8.setText(D38);
              Num9.setText(D39);
              Num10.setText(D40);
              
              IsDisp = false;
            }
            N1.close();
            N2.close();
            N3.close();
            N4.close();
            N5.close();
            N6.close();
            N7.close();
            N8.close();
            N9.close();
            N10.close();
            
            CID1.close();
            CID2.close();
            CID3.close();
            CID4.close();
            CID5.close();
            CID6.close();
            CID7.close();
            CID8.close();
            CID9.close();
            CID10.close();
            
            CAdd1.close();
            CAdd2.close();
            CAdd3.close();
            CAdd4.close();
            CAdd5.close();
            CAdd6.close();
            CAdd7.close();
            CAdd8.close();
            CAdd9.close();
            CAdd10.close();
            
            CNum1.close();
            CNum2.close();
            CNum3.close();
            CNum4.close();
            CNum5.close();
            CNum6.close();
            CNum7.close();
            CNum8.close();
            CNum9.close();
            CNum10.close();
          } catch (FileNotFoundException e) {
            System.out.println("An error occurred.");
          }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRAME11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRAME11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRAME11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRAME11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRAME11().setVisible(true);
            }
        });
    }
    
    private boolean IsDisp = false;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Add1;
    private javax.swing.JTextField Add10;
    private javax.swing.JTextField Add2;
    private javax.swing.JTextField Add3;
    private javax.swing.JTextField Add4;
    private javax.swing.JTextField Add5;
    private javax.swing.JTextField Add6;
    private javax.swing.JTextField Add7;
    private javax.swing.JTextField Add8;
    private javax.swing.JTextField Add9;
    private javax.swing.JTextField ID1;
    private javax.swing.JTextField ID10;
    private javax.swing.JTextField ID2;
    private javax.swing.JTextField ID3;
    private javax.swing.JTextField ID4;
    private javax.swing.JTextField ID5;
    private javax.swing.JTextField ID6;
    private javax.swing.JTextField ID7;
    private javax.swing.JTextField ID8;
    private javax.swing.JTextField ID9;
    private javax.swing.JTextField Num1;
    private javax.swing.JTextField Num10;
    private javax.swing.JTextField Num2;
    private javax.swing.JTextField Num3;
    private javax.swing.JTextField Num4;
    private javax.swing.JTextField Num5;
    private javax.swing.JTextField Num6;
    private javax.swing.JTextField Num7;
    private javax.swing.JTextField Num8;
    private javax.swing.JTextField Num9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
