/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PharmacyUI;

import java.io.FileWriter;
import java.io.IOException;
import static java.lang.System.exit;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class FRAME9 extends javax.swing.JFrame {

    /**
     * Creates new form FRAME7
     */
    public FRAME9() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        CName = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        Number = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PMS");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 255, 255));
        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("ADD DATA");

        jTextField3.setBackground(new java.awt.Color(204, 255, 255));
        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField3.setText("Do you want me to display the customer data?");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Yes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("No");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(204, 255, 255));
        jTextField4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField4.setText("CUSTOMER DATA");

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(204, 255, 255));
        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("Customer's Name");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        CName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(204, 255, 255));
        jTextField6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("Customer's ID");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        ID.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(204, 255, 255));
        jTextField8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("Customer's PhoneNumber");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        Address.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(204, 255, 255));
        jTextField10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("Customer's Address");
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        Number.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 255, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(33, 33, 33)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CName, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Number, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Pharmacy P = new Pharmacy();
        JOptionPane.showMessageDialog(null, "Goodbye " + P.getName());
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        FRAME11 jf11 = new FRAME11();
            jf11.show();
            
            dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JFRAME5 jf5 = new JFRAME5();
            jf5.show();
            
            dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!(CName.getText().equals("")))
        {
            WriteToFile();   
        }
        else {
             JOptionPane.showMessageDialog(null, "Please fill the form.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    private void WriteToFile() {
        String S = (String) jComboBox1.getSelectedItem();
      int temp = Integer.parseInt(S);
        
      if(temp == 1)
      {
        try {
        FileWriter WN = new FileWriter("f1Name.txt");
        FileWriter WID = new FileWriter("f1ID.txt");
        FileWriter WAdd = new FileWriter("f1Add.txt");
        FileWriter WNum = new FileWriter("f1Num.txt");
        String NameData = CName.getText();
        String IDData = ID.getText();
        String AddData = Address.getText();
        String NumData = Number.getText();
        WN.write(NameData);
        WID.write(IDData);
        WAdd.write(AddData);
        WNum.write(NumData);
        WNum.close();
        WAdd.close();
        WID.close();
        WN.close();
        CName.setText("");
        ID.setText("");
        Address.setText("");
        Number.setText("");
      } catch (IOException e) {
        System.out.println("An error occurred.");
        e.printStackTrace();
      }
     }
     else if(temp == 2)
      {
        try {
        FileWriter WN = new FileWriter("f2Name.txt");
        FileWriter WID = new FileWriter("f2ID.txt");
        FileWriter WAdd = new FileWriter("f2Add.txt");
        FileWriter WNum = new FileWriter("f2Num.txt");
        String NameData = CName.getText();
        String IDData = ID.getText();
        String AddData = Address.getText();
        String NumData = Number.getText();
        WN.write(NameData);
        WID.write(IDData);
        WAdd.write(AddData);
        WNum.write(NumData);
        WNum.close();
        WAdd.close();
        WID.close();
        WN.close();
        CName.setText("");
        ID.setText("");
        Address.setText("");
        Number.setText("");
      } catch (IOException e) {
        System.out.println("An error occurred.");
        e.printStackTrace();
      }
     }
      else if(temp == 3)
      {
        try {
        FileWriter WN = new FileWriter("f3Name.txt");
        FileWriter WID = new FileWriter("f3ID.txt");
        FileWriter WAdd = new FileWriter("f3Add.txt");
        FileWriter WNum = new FileWriter("f3Num.txt");
        String NameData = CName.getText();
        String IDData = ID.getText();
        String AddData = Address.getText();
        String NumData = Number.getText();
        WN.write(NameData);
        WID.write(IDData);
        WAdd.write(AddData);
        WNum.write(NumData);
        WNum.close();
        WAdd.close();
        WID.close();
        WN.close();
        CName.setText("");
        ID.setText("");
        Address.setText("");
        Number.setText("");
      } catch (IOException e) {
        System.out.println("An error occurred.");
        e.printStackTrace();
      }
     }
      else if(temp == 4)
      {
        try {
        FileWriter WN = new FileWriter("f4Name.txt");
        FileWriter WID = new FileWriter("f4ID.txt");
        FileWriter WAdd = new FileWriter("f4Add.txt");
        FileWriter WNum = new FileWriter("f4Num.txt");
        String NameData = CName.getText();
        String IDData = ID.getText();
        String AddData = Address.getText();
        String NumData = Number.getText();
        WN.write(NameData);
        WID.write(IDData);
        WAdd.write(AddData);
        WNum.write(NumData);
        WNum.close();
        WAdd.close();
        WID.close();
        WN.close();
        CName.setText("");
        ID.setText("");
        Address.setText("");
        Number.setText("");
      } catch (IOException e) {
        System.out.println("An error occurred.");
        e.printStackTrace();
      }
     }
      else if(temp == 5)
      {
        try {
        FileWriter WN = new FileWriter("f5Name.txt");
        FileWriter WID = new FileWriter("f5ID.txt");
        FileWriter WAdd = new FileWriter("f5Add.txt");
        FileWriter WNum = new FileWriter("f5Num.txt");
        String NameData = CName.getText();
        String IDData = ID.getText();
        String AddData = Address.getText();
        String NumData = Number.getText();
        WN.write(NameData);
        WID.write(IDData);
        WAdd.write(AddData);
        WNum.write(NumData);
        WNum.close();
        WAdd.close();
        WID.close();
        WN.close();
        CName.setText("");
        ID.setText("");
        Address.setText("");
        Number.setText("");
      } catch (IOException e) {
        System.out.println("An error occurred.");
        e.printStackTrace();
      }
     }
      else if(temp == 5)
      {
        try {
        FileWriter WN = new FileWriter("f5Name.txt");
        FileWriter WID = new FileWriter("f5ID.txt");
        FileWriter WAdd = new FileWriter("f5Add.txt");
        FileWriter WNum = new FileWriter("f5Num.txt");
        String NameData = CName.getText();
        String IDData = ID.getText();
        String AddData = Address.getText();
        String NumData = Number.getText();
        WN.write(NameData);
        WID.write(IDData);
        WAdd.write(AddData);
        WNum.write(NumData);
        WNum.close();
        WAdd.close();
        WID.close();
        WN.close();
        CName.setText("");
        ID.setText("");
        Address.setText("");
        Number.setText("");
      } catch (IOException e) {
        System.out.println("An error occurred.");
        e.printStackTrace();
      }
     }
      else if(temp == 6)
      {
        try {
        FileWriter WN = new FileWriter("f6Name.txt");
        FileWriter WID = new FileWriter("f6ID.txt");
        FileWriter WAdd = new FileWriter("f6Add.txt");
        FileWriter WNum = new FileWriter("f6Num.txt");
        String NameData = CName.getText();
        String IDData = ID.getText();
        String AddData = Address.getText();
        String NumData = Number.getText();
        WN.write(NameData);
        WID.write(IDData);
        WAdd.write(AddData);
        WNum.write(NumData);
        WNum.close();
        WAdd.close();
        WID.close();
        WN.close();
        CName.setText("");
        ID.setText("");
        Address.setText("");
        Number.setText("");
      } catch (IOException e) {
        System.out.println("An error occurred.");
        e.printStackTrace();
      }
     }
      else if(temp == 7)
      {
        try {
        FileWriter WN = new FileWriter("f7Name.txt");
        FileWriter WID = new FileWriter("f7ID.txt");
        FileWriter WAdd = new FileWriter("f7Add.txt");
        FileWriter WNum = new FileWriter("f7Num.txt");
        String NameData = CName.getText();
        String IDData = ID.getText();
        String AddData = Address.getText();
        String NumData = Number.getText();
        WN.write(NameData);
        WID.write(IDData);
        WAdd.write(AddData);
        WNum.write(NumData);
        WNum.close();
        WAdd.close();
        WID.close();
        WN.close();
        CName.setText("");
        ID.setText("");
        Address.setText("");
        Number.setText("");
      } catch (IOException e) {
        System.out.println("An error occurred.");
        e.printStackTrace();
      }
     }
      else if(temp == 8)
      {
        try {
        FileWriter WN = new FileWriter("f8Name.txt");
        FileWriter WID = new FileWriter("f8ID.txt");
        FileWriter WAdd = new FileWriter("f8Add.txt");
        FileWriter WNum = new FileWriter("f8Num.txt");
        String NameData = CName.getText();
        String IDData = ID.getText();
        String AddData = Address.getText();
        String NumData = Number.getText();
        WN.write(NameData);
        WID.write(IDData);
        WAdd.write(AddData);
        WNum.write(NumData);
        WNum.close();
        WAdd.close();
        WID.close();
        WN.close();
        CName.setText("");
        ID.setText("");
        Address.setText("");
        Number.setText("");
      } catch (IOException e) {
        System.out.println("An error occurred.");
        e.printStackTrace();
      }
     }
      else if(temp == 9)
      {
        try {
        FileWriter WN = new FileWriter("f9Name.txt");
        FileWriter WID = new FileWriter("f9ID.txt");
        FileWriter WAdd = new FileWriter("f9Add.txt");
        FileWriter WNum = new FileWriter("f9Num.txt");
        String NameData = CName.getText();
        String IDData = ID.getText();
        String AddData = Address.getText();
        String NumData = Number.getText();
        WN.write(NameData);
        WID.write(IDData);
        WAdd.write(AddData);
        WNum.write(NumData);
        WNum.close();
        WAdd.close();
        WID.close();
        WN.close();
        CName.setText("");
        ID.setText("");
        Address.setText("");
        Number.setText("");
      } catch (IOException e) {
        System.out.println("An error occurred.");
        e.printStackTrace();
      }
     }
      else if(temp == 10)
      {
        try {
        FileWriter WN = new FileWriter("f10Name.txt");
        FileWriter WID = new FileWriter("f10ID.txt");
        FileWriter WAdd = new FileWriter("f10Add.txt");
        FileWriter WNum = new FileWriter("f10Num.txt");
        String NameData = CName.getText();
        String IDData = ID.getText();
        String AddData = Address.getText();
        String NumData = Number.getText();
        WN.write(NameData);
        WID.write(IDData);
        WAdd.write(AddData);
        WNum.write(NumData);
        WNum.close();
        WAdd.close();
        WID.close();
        WN.close();
        CName.setText("");
        ID.setText("");
        Address.setText("");
        Number.setText("");
      } catch (IOException e) {
        System.out.println("An error occurred.");
        e.printStackTrace();
      }
      }
    }
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRAME9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRAME9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRAME9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRAME9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRAME9().setVisible(true);
            }
        });
    }
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField CName;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Number;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
